[package]
name = "rosetta-iota"
version = "0.1.0"
authors = ["Bernardo A. Rodrigues <bernardo.araujo@iota.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
warp = "0.3"
structopt = "0.3"
thiserror = "1.0"
url = "2.1"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["macros"] }
bcs = "0.1.2"
hex = "0.4"
env_logger = "0.7"
futures = "0.3"
iota-core = { git = "https://github.com/iotaledger/iota.rs", branch = "dev" }
