version: '3.3'

services:
  hornet:
    image: iotaledger/hornet:chrysalis2-preview
    restart: "no"
    working_dir: /app
    expose:
      # Node API
      - "14265"
      # libp2p/gossip protocol
      - "15600"
    ports:
      - "127.0.0.1:14265:14265/tcp"
      - "0.0.0.0:15600:15600/tcp"
    volumes:
      - './hornet/config.json:/app/config.json:ro'
      - './hornet/peering.json:/app/peering.json'
      - './data:/data'
      - '/etc/ssl/certs:/etc/ssl/certs:ro'
      - '/etc/localtime:/etc/localtime:ro'

  rosetta:
    build: .
    command: --bind-addr 0.0.0.0:3030 --network $NETWORK --bech32-hrp $BECH32_HRP --tx-tag $TX_TAG --node-url http://hornet:14265 --mode $MODE
    restart: "always"
    environment:
      RUST_LOG: info
    expose:
      # Rosetta API
      - "3030"
    ports:
      - "0.0.0.0:3030:3030/tcp"
